services:
  postgres:
    image: postgres:15-alpine
    container_name: serbian-vocab-db
    environment:
      POSTGRES_USER: vocab_user
      POSTGRES_PASSWORD: vocab_pass
      POSTGRES_DB: serbian_vocabulary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vocab-network

  redis:
    image: redis:7-alpine
    container_name: serbian-vocab-redis
    ports:
      - "6379:6379"
    networks:
      - vocab-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  backend:
    build: ./backend
    container_name: serbian-vocab-backend
    environment:
      DATABASE_URL: postgresql://vocab_user:vocab_pass@postgres:5432/serbian_vocabulary
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - vocab-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  cache-updater:
    build: ./backend
    container_name: serbian-vocab-cache-updater
    environment:
      DATABASE_URL: postgresql://vocab_user:vocab_pass@postgres:5432/serbian_vocabulary
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - vocab-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: python cache_updater.py

  image-sync-service:
    build: ./image-sync-service
    container_name: serbian-vocab-image-sync
    environment:
      REDIS_URL: redis://redis:6379
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/image-sync.log
    depends_on:
      - redis
    networks:
      - vocab-network
    volumes:
      - ./image-sync-service:/app
      - image_sync_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.from_url('redis://redis:6379').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build: ./frontend
    container_name: serbian-vocab-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vocab-network

volumes:
  postgres_data:
  redis_data:
  image_sync_logs:

networks:
  vocab-network:
    driver: bridge
