import os
import sys

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

# Load environment variables
load_dotenv()

# Database configuration
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    print("Error: DATABASE_URL not set")
    sys.exit(1)

# Create engine
engine = create_engine(DATABASE_URL)

# Top 100 words by category
TOP_100_WORDS = {
    "General": [
        # Common everyday words
        ("ja", "I/me"),
        ("ti", "you"),
        ("on", "he"),
        ("ona", "she"),
        ("mi", "we"),
        ("vi", "you (plural/formal)"),
        ("oni", "they"),
        ("biti", "to be"),
        ("imati", "to have"),
        ("moći", "can/to be able"),
        ("hteti", "to want"),
        ("raditi", "to work"),
        ("živeti", "to live"),
        ("videti", "to see"),
        ("znati", "to know"),
        ("doći", "to come"),
        ("otići", "to go/leave"),
        ("reći", "to say"),
        ("misliti", "to think"),
        ("dati", "to give"),
        ("uzeti", "to take"),
        ("naći", "to find"),
        ("gledati", "to watch/look"),
        ("čuti", "to hear"),
        ("osećati", "to feel"),
        ("dan", "day"),
        ("noć", "night"),
        ("jutro", "morning"),
        ("veče", "evening"),
        ("vreme", "time/weather"),
        ("godina", "year"),
        ("mesec", "month/moon"),
        ("nedelja", "week/Sunday"),
        ("danas", "today"),
        ("sutra", "tomorrow"),
        ("juče", "yesterday"),
        ("sada", "now"),
        ("posle", "after"),
        ("pre", "before"),
        ("ovde", "here"),
        ("tamo", "there"),
        ("gore", "up"),
        ("dole", "down"),
        ("levo", "left"),
        ("desno", "right"),
        ("veliko", "big"),
        ("malo", "small"),
        ("dobro", "good/well"),
        ("loše", "bad"),
        ("lepo", "beautiful/nice"),
        ("ružno", "ugly"),
        ("novo", "new"),
        ("staro", "old"),
        ("toplo", "warm"),
        ("hladno", "cold"),
        ("brzo", "fast"),
        ("sporo", "slow"),
        ("lako", "easy"),
        ("teško", "difficult/heavy"),
        ("i", "and"),
        ("ili", "or"),
        ("ali", "but"),
        ("jer", "because"),
        ("ako", "if"),
        ("kada", "when"),
        ("gde", "where"),
        ("kako", "how"),
        ("zašto", "why"),
        ("šta", "what"),
        ("ko", "who"),
        ("koji", "which"),
        ("da", "yes/that"),
        ("ne", "no/not"),
        ("molim", "please"),
        ("hvala", "thank you"),
        ("izvini", "sorry/excuse me"),
        ("zdravo", "hello"),
        ("doviđenja", "goodbye"),
        ("dobro jutro", "good morning"),
        ("dobro veče", "good evening"),
        ("laku noć", "good night"),
        ("jedan", "one"),
        ("dva", "two"),
        ("tri", "three"),
        ("četiri", "four"),
        ("pet", "five"),
        ("šest", "six"),
        ("sedam", "seven"),
        ("osam", "eight"),
        ("devet", "nine"),
        ("deset", "ten"),
        ("sto", "hundred"),
        ("hiljada", "thousand"),
        ("novac", "money"),
        ("cena", "price"),
        ("jeftino", "cheap"),
        ("skupo", "expensive"),
        ("mnogo", "much/many"),
        ("malo", "little/few"),
        ("sve", "all/everything"),
        ("ništa", "nothing"),
        ("nešto", "something"),
        ("neko", "someone"),
    ],
    "Family": [
        ("porodica", "family"),
        ("majka", "mother"),
        ("otac", "father"),
        ("sin", "son"),
        ("ćerka", "daughter"),
        ("brat", "brother"),
        ("sestra", "sister"),
        ("deda", "grandfather"),
        ("baba", "grandmother"),
        ("unuk", "grandson"),
        ("unuka", "granddaughter"),
        ("tetka", "aunt"),
        ("teča", "uncle (aunt's husband)"),
        ("ujak", "uncle (mother's brother)"),
        ("stric", "uncle (father's brother)"),
        ("bratanac", "nephew (brother's son)"),
        ("bratanica", "niece (brother's daughter)"),
        ("sestrić", "nephew (sister's son)"),
        ("sestričina", "niece (sister's daughter)"),
        ("rođak", "cousin (male)"),
        ("rođaka", "cousin (female)"),
        ("muž", "husband"),
        ("žena", "wife"),
        ("suprug", "spouse (male)"),
        ("supruga", "spouse (female)"),
        ("zet", "son-in-law"),
        ("snaja", "daughter-in-law"),
        ("svekar", "father-in-law (husband's father)"),
        ("svekrva", "mother-in-law (husband's mother)"),
        ("tast", "father-in-law (wife's father)"),
        ("tašta", "mother-in-law (wife's mother)"),
        ("dete", "child"),
        ("beba", "baby"),
        ("tinejdžer", "teenager"),
        ("odrastao", "adult"),
        ("stariji", "elderly"),
        ("verenica", "fiancée"),
        ("verenik", "fiancé"),
        ("momak", "boyfriend"),
        ("devojka", "girlfriend"),
        ("brak", "marriage"),
        ("venčanje", "wedding"),
        ("razvod", "divorce"),
        ("rođenje", "birth"),
        ("rođendan", "birthday"),
        ("godišnjica", "anniversary"),
        ("krštenje", "baptism"),
        ("sahrana", "funeral"),
        ("dom", "home"),
        ("kuća", "house"),
        ("stan", "apartment"),
        ("soba", "room"),
        ("kuhinja", "kitchen"),
        ("dnevna soba", "living room"),
        ("spavaća soba", "bedroom"),
        ("kupatilo", "bathroom"),
        ("vrt", "garden"),
        ("porodično stablo", "family tree"),
        ("predak", "ancestor"),
        ("potomak", "descendant"),
        ("rodbina", "relatives"),
        ("svadba", "wedding ceremony"),
        ("mladoženja", "groom"),
        ("mlada", "bride"),
        ("kum", "best man/godfather"),
        ("kuma", "maid of honor/godmother"),
        ("kumče", "godchild"),
        ("bratstvo", "brotherhood"),
        ("sestrstvo", "sisterhood"),
        ("očinstvo", "fatherhood"),
        ("majčinstvo", "motherhood"),
        ("roditeljstvo", "parenthood"),
        ("usvojiti", "to adopt"),
        ("usvojeno dete", "adopted child"),
        ("hranitelj", "foster parent"),
        ("staratelj", "guardian"),
        ("naslednik", "heir"),
        ("nasledstvo", "inheritance"),
        ("porodična tradicija", "family tradition"),
        ("porodične vrednosti", "family values"),
        ("generacija", "generation"),
        ("blizanci", "twins"),
        ("trojke", "triplets"),
        ("prvorođeni", "firstborn"),
        ("mezimac", "youngest child"),
        ("jedinac", "only child"),
        ("polu-brat", "half-brother"),
        ("polu-sestra", "half-sister"),
        ("očuh", "stepfather"),
        ("maćeha", "stepmother"),
        ("pastorče", "stepchild"),
        ("usvojitelj", "adoptive parent"),
        ("biološki roditelj", "biological parent"),
        ("vaspitati", "to raise/educate"),
        ("brinuti se", "to take care of"),
        ("voleti", "to love"),
        ("poštovati", "to respect"),
        ("podržavati", "to support"),
        ("okupiti se", "to gather"),
        ("proslaviti", "to celebrate"),
    ],
    "Work": [
        ("posao", "job/work"),
        ("karijera", "career"),
        ("zaposlenje", "employment"),
        ("kancelarija", "office"),
        ("firma", "company"),
        ("preduzeće", "enterprise"),
        ("kompanija", "company"),
        ("šef", "boss"),
        ("menadžer", "manager"),
        ("direktor", "director"),
        ("zaposleni", "employee"),
        ("kolega", "colleague"),
        ("tim", "team"),
        ("sastanak", "meeting"),
        ("projekat", "project"),
        ("zadatak", "task"),
        ("rok", "deadline"),
        ("raspored", "schedule"),
        ("smena", "shift"),
        ("plata", "salary"),
        ("zarada", "earnings"),
        ("bonus", "bonus"),
        ("odmor", "vacation"),
        ("pauza", "break"),
        ("prekovremeni rad", "overtime"),
        ("radno vreme", "working hours"),
        ("puno radno vreme", "full-time"),
        ("pola radnog vremena", "part-time"),
        ("ugovor", "contract"),
        ("intervju", "interview"),
        ("CV", "resume"),
        ("biografija", "biography"),
        ("kvalifikacije", "qualifications"),
        ("iskustvo", "experience"),
        ("veštine", "skills"),
        ("obuka", "training"),
        ("napredovanje", "promotion"),
        ("otkaz", "dismissal/resignation"),
        ("penzija", "pension"),
        ("penzionisati se", "to retire"),
        ("proizvod", "product"),
        ("usluga", "service"),
        ("kupac", "customer"),
        ("klijent", "client"),
        ("prodaja", "sales"),
        ("marketing", "marketing"),
        ("finansije", "finance"),
        ("računovodstvo", "accounting"),
        ("ljudski resursi", "human resources"),
        ("razvoj", "development"),
        ("istraživanje", "research"),
        ("proizvodnja", "production"),
        ("kvalitet", "quality"),
        ("efikasnost", "efficiency"),
        ("produktivnost", "productivity"),
        ("cilj", "goal"),
        ("strategija", "strategy"),
        ("plan", "plan"),
        ("budžet", "budget"),
        ("izveštaj", "report"),
        ("prezentacija", "presentation"),
        ("komunikacija", "communication"),
        ("saradnja", "cooperation"),
        ("konkurencija", "competition"),
        ("tržište", "market"),
        ("potrošač", "consumer"),
        ("ponuda", "offer"),
        ("potražnja", "demand"),
        ("profit", "profit"),
        ("gubitak", "loss"),
        ("investicija", "investment"),
        ("rizik", "risk"),
        ("uspeh", "success"),
        ("neuspeh", "failure"),
        ("pregovaranje", "negotiation"),
        ("potpisati", "to sign"),
        ("organizovati", "to organize"),
        ("planirati", "to plan"),
        ("upravljati", "to manage"),
        ("nadgledati", "to supervise"),
        ("proceniti", "to evaluate"),
        ("analizirati", "to analyze"),
        ("rešiti", "to solve"),
        ("poboljšati", "to improve"),
        ("dostići", "to achieve"),
        ("sarađivati", "to collaborate"),
        ("komunicirati", "to communicate"),
        ("predstaviti", "to present"),
        ("pregovarati", "to negotiate"),
        ("zaposliti", "to hire"),
        ("otpustiti", "to fire"),
        ("trenirati", "to train"),
        ("motivisati", "to motivate"),
        ("nagrađivati", "to reward"),
        ("dokumentacija", "documentation"),
        ("procedura", "procedure"),
        ("politika", "policy"),
        ("standard", "standard"),
        ("sertifikat", "certificate"),
        ("licenca", "license"),
        ("inovacija", "innovation"),
        ("tehnologija", "technology"),
    ],
    "Entertainment": [
        ("zabava", "entertainment/fun"),
        ("film", "movie"),
        ("bioskop", "cinema"),
        ("pozorište", "theater"),
        ("predstava", "play/performance"),
        ("koncert", "concert"),
        ("muzika", "music"),
        ("pesma", "song"),
        ("ples", "dance"),
        ("igra", "game"),
        ("sport", "sport"),
        ("fudbal", "football/soccer"),
        ("košarka", "basketball"),
        ("tenis", "tennis"),
        ("plivanje", "swimming"),
        ("trčanje", "running"),
        ("vežbanje", "exercise"),
        ("teretana", "gym"),
        ("knjiga", "book"),
        ("roman", "novel"),
        ("poezija", "poetry"),
        ("časopis", "magazine"),
        ("novine", "newspaper"),
        ("televizija", "television"),
        ("serija", "TV series"),
        ("emisija", "TV show"),
        ("radio", "radio"),
        ("internet", "internet"),
        ("društvene mreže", "social media"),
        ("video igra", "video game"),
        ("hobi", "hobby"),
        ("slikanje", "painting"),
        ("crtanje", "drawing"),
        ("fotografija", "photography"),
        ("kuvanje", "cooking"),
        ("pecanje", "fishing"),
        ("lov", "hunting"),
        ("kampovanje", "camping"),
        ("planinarenje", "hiking"),
        ("putovanje", "travel"),
        ("odmor", "vacation/holiday"),
        ("plaža", "beach"),
        ("more", "sea"),
        ("planina", "mountain"),
        ("jezero", "lake"),
        ("reka", "river"),
        ("park", "park"),
        ("muzej", "museum"),
        ("galerija", "gallery"),
        ("izložba", "exhibition"),
        ("festival", "festival"),
        ("karneval", "carnival"),
        ("cirkus", "circus"),
        ("zabavni park", "amusement park"),
        ("zoo vrt", "zoo"),
        ("akvarijum", "aquarium"),
        ("restoran", "restaurant"),
        ("kafić", "café"),
        ("bar", "bar"),
        ("klub", "club"),
        ("diskoteka", "disco"),
        ("žurka", "party"),
        ("proslava", "celebration"),
        ("rođendanska žurka", "birthday party"),
        ("venčanje", "wedding"),
        ("diploma", "graduation"),
        ("Nova godina", "New Year"),
        ("Božić", "Christmas"),
        ("Uskrs", "Easter"),
        ("praznik", "holiday"),
        ("slavlje", "festivity"),
        ("vatromet", "fireworks"),
        ("parada", "parade"),
        ("kostim", "costume"),
        ("maska", "mask"),
        ("poklon", "gift"),
        ("iznenađenje", "surprise"),
        ("smeh", "laughter"),
        ("šala", "joke"),
        ("vicevi", "jokes"),
        ("komedija", "comedy"),
        ("drama", "drama"),
        ("akcija", "action"),
        ("avantura", "adventure"),
        ("fantazija", "fantasy"),
        ("naučna fantastika", "science fiction"),
        ("horor", "horror"),
        ("triler", "thriller"),
        ("romantika", "romance"),
        ("dokumentarac", "documentary"),
        ("animacija", "animation"),
        ("crtani film", "cartoon"),
        ("glumac", "actor"),
        ("glumica", "actress"),
        ("režiser", "director"),
        ("producent", "producer"),
        ("scenarista", "screenwriter"),
        ("pevač", "singer (male)"),
        ("pevačica", "singer (female)"),
        ("muzičar", "musician"),
        ("bend", "band"),
        ("orkestar", "orchestra"),
        ("instrument", "instrument"),
    ],
    "IT": [
        ("računar", "computer"),
        ("laptop", "laptop"),
        ("telefon", "phone"),
        ("tablet", "tablet"),
        ("ekran", "screen"),
        ("monitor", "monitor"),
        ("tastatura", "keyboard"),
        ("miš", "mouse"),
        ("štampač", "printer"),
        ("skener", "scanner"),
        ("kamera", "camera"),
        ("slušalice", "headphones"),
        ("zvučnici", "speakers"),
        ("mikrofon", "microphone"),
        ("internet", "internet"),
        ("veb sajt", "website"),
        ("aplikacija", "application"),
        ("program", "program"),
        ("softver", "software"),
        ("hardver", "hardware"),
        ("operativni sistem", "operating system"),
        ("fajl", "file"),
        ("folder", "folder"),
        ("dokument", "document"),
        ("podaci", "data"),
        ("baza podataka", "database"),
        ("server", "server"),
        ("mreža", "network"),
        ("konekcija", "connection"),
        ("bežični", "wireless"),
        ("kabel", "cable"),
        ("ruter", "router"),
        ("modem", "modem"),
        ("signal", "signal"),
        ("brzina", "speed"),
        ("download", "download"),
        ("upload", "upload"),
        ("instalirati", "to install"),
        ("deinstalirati", "to uninstall"),
        ("ažurirati", "to update"),
        ("restartovati", "to restart"),
        ("pokrenuti", "to start/run"),
        ("zatvoriti", "to close"),
        ("sačuvati", "to save"),
        ("obrisati", "to delete"),
        ("kopirati", "to copy"),
        ("nalepiti", "to paste"),
        ("pretraživati", "to search"),
        ("kliknuti", "to click"),
        ("prevući", "to drag"),
        ("prijaviti se", "to log in"),
        ("odjaviti se", "to log out"),
        ("lozinka", "password"),
        ("korisničko ime", "username"),
        ("nalog", "account"),
        ("profil", "profile"),
        ("postavke", "settings"),
        ("sigurnost", "security"),
        ("privatnost", "privacy"),
        ("virus", "virus"),
        ("antivirus", "antivirus"),
        ("zaštitni zid", "firewall"),
        ("rezervna kopija", "backup"),
        ("oblak", "cloud"),
        ("memorija", "memory"),
        ("procesor", "processor"),
        ("grafička kartica", "graphics card"),
        ("matična ploča", "motherboard"),
        ("napajanje", "power supply"),
        ("hlađenje", "cooling"),
        ("kućište", "case"),
        ("port", "port"),
        ("USB", "USB"),
        ("Bluetooth", "Bluetooth"),
        ("Wi-Fi", "Wi-Fi"),
        ("e-pošta", "email"),
        ("poruka", "message"),
        ("chat", "chat"),
        ("video poziv", "video call"),
        ("konferencija", "conference"),
        ("prezentacija", "presentation"),
        ("tablica", "spreadsheet"),
        ("grafik", "chart/graph"),
        ("kod", "code"),
        ("programiranje", "programming"),
        ("razvoj", "development"),
        ("testiranje", "testing"),
        ("greška", "error/bug"),
        ("popravka", "fix"),
        ("verzija", "version"),
        ("nadogradnja", "upgrade"),
        ("kompatibilnost", "compatibility"),
        ("performanse", "performance"),
        ("optimizacija", "optimization"),
        ("algoritam", "algorithm"),
        ("veštačka inteligencija", "artificial intelligence"),
        ("mašinsko učenje", "machine learning"),
        ("virtuelna realnost", "virtual reality"),
        ("kriptovaluta", "cryptocurrency"),
        ("blokčejn", "blockchain"),
        ("sajber bezbednost", "cybersecurity"),
        ("hakovanje", "hacking"),
        ("enkripcija", "encryption"),
    ],
    "Music": [
        ("muzika", "music"),
        ("pesma", "song"),
        ("melodija", "melody"),
        ("ritam", "rhythm"),
        ("harmonija", "harmony"),
        ("nota", "note"),
        ("akord", "chord"),
        ("tonalitet", "key"),
        ("tempo", "tempo"),
        ("takt", "beat/measure"),
        ("partitura", "score"),
        ("kompozicija", "composition"),
        ("aranžman", "arrangement"),
        ("izvođenje", "performance"),
        ("koncert", "concert"),
        ("proba", "rehearsal"),
        ("snimanje", "recording"),
        ("studio", "studio"),
        ("album", "album"),
        ("singl", "single"),
        ("hit", "hit"),
        ("lista", "chart"),
        ("žanr", "genre"),
        ("rok", "rock"),
        ("pop", "pop"),
        ("džez", "jazz"),
        ("klasična muzika", "classical music"),
        ("narodna muzika", "folk music"),
        ("elektronska muzika", "electronic music"),
        ("hip hop", "hip hop"),
        ("rep", "rap"),
        ("bluz", "blues"),
        ("kantri", "country"),
        ("metal", "metal"),
        ("pank", "punk"),
        ("reggae", "reggae"),
        ("soul", "soul"),
        ("funk", "funk"),
        ("opera", "opera"),
        ("simfonija", "symphony"),
        ("sonata", "sonata"),
        ("instrument", "instrument"),
        ("gitara", "guitar"),
        ("klavir", "piano"),
        ("violina", "violin"),
        ("bubnjevi", "drums"),
        ("bas gitara", "bass guitar"),
        ("saksofon", "saxophone"),
        ("truba", "trumpet"),
        ("flauta", "flute"),
        ("harmonika", "accordion"),
        ("sintisajzer", "synthesizer"),
        ("mikrofon", "microphone"),
        ("pojačalo", "amplifier"),
        ("zvučnik", "speaker"),
        ("slušalice", "headphones"),
        ("muzičar", "musician"),
        ("pevač", "singer (male)"),
        ("pevačica", "singer (female)"),
        ("gitarista", "guitarist"),
        ("pijanista", "pianist"),
        ("bubnjar", "drummer"),
        ("basista", "bassist"),
        ("violinista", "violinist"),
        ("kompozitor", "composer"),
        ("dirigent", "conductor"),
        ("producent", "producer"),
        ("DJ", "DJ"),
        ("bend", "band"),
        ("grupa", "group"),
        ("orkestar", "orchestra"),
        ("hor", "choir"),
        ("ansambl", "ensemble"),
        ("solo", "solo"),
        ("duet", "duet"),
        ("trio", "trio"),
        ("kvartet", "quartet"),
        ("refren", "chorus/refrain"),
        ("strofa", "verse"),
        ("most", "bridge"),
        ("intro", "intro"),
        ("outro", "outro"),
        ("tekst", "lyrics"),
        ("pisac tekstova", "lyricist"),
        ("vokali", "vocals"),
        ("backing vokali", "backing vocals"),
        ("akustični", "acoustic"),
        ("električni", "electric"),
        ("uživo", "live"),
        ("playback", "playback"),
        ("remix", "remix"),
        ("cover", "cover"),
        ("original", "original"),
        ("autorska prava", "copyright"),
        ("izdavač", "publisher/label"),
        ("turne", "tour"),
        ("festival", "festival"),
        ("nagrada", "award"),
        ("Grammy", "Grammy"),
        ("platinasti", "platinum"),
        ("zlatni", "gold"),
    ],
    "Food": [
        ("hrana", "food"),
        ("jelo", "dish/meal"),
        ("doručak", "breakfast"),
        ("ručak", "lunch"),
        ("večera", "dinner"),
        ("užina", "snack"),
        ("hleb", "bread"),
        ("meso", "meat"),
        ("piletina", "chicken"),
        ("svinjetina", "pork"),
        ("govedina", "beef"),
        ("riba", "fish"),
        ("povrće", "vegetables"),
        ("voće", "fruit"),
        ("jabuka", "apple"),
        ("banana", "banana"),
        ("narandža", "orange"),
        ("limun", "lemon"),
        ("jagoda", "strawberry"),
        ("grožđe", "grapes"),
        ("lubenica", "watermelon"),
        ("krompir", "potato"),
        ("paradajz", "tomato"),
        ("krastavac", "cucumber"),
        ("luk", "onion"),
        ("beli luk", "garlic"),
        ("paprika", "pepper"),
        ("šargarepa", "carrot"),
        ("kupus", "cabbage"),
        ("salata", "lettuce/salad"),
        ("pasulj", "beans"),
        ("grašak", "peas"),
        ("kukuruz", "corn"),
        ("pirinač", "rice"),
        ("testenina", "pasta"),
        ("sir", "cheese"),
        ("mleko", "milk"),
        ("jogurt", "yogurt"),
        ("pavlaka", "sour cream"),
        ("puter", "butter"),
        ("jaje", "egg"),
        ("brašno", "flour"),
        ("šećer", "sugar"),
        ("so", "salt"),
        ("biber", "pepper (spice)"),
        ("ulje", "oil"),
        ("sirće", "vinegar"),
        ("med", "honey"),
        ("džem", "jam"),
        ("čokolada", "chocolate"),
        ("kolač", "cake"),
        ("torta", "cake/tort"),
        ("keks", "cookie/biscuit"),
        ("sladoled", "ice cream"),
        ("pica", "pizza"),
        ("sendvič", "sandwich"),
        ("burger", "burger"),
        ("pomfrit", "french fries"),
        ("supa", "soup"),
        ("čorba", "thick soup"),
        ("salata", "salad"),
        ("sos", "sauce"),
        ("začin", "spice"),
        ("kuvati", "to cook"),
        ("peći", "to bake/roast"),
        ("pržiti", "to fry"),
        ("kuvati na pari", "to steam"),
        ("grilovati", "to grill"),
        ("seći", "to cut"),
        ("mešati", "to mix"),
        ("služiti", "to serve"),
        ("jesti", "to eat"),
        ("piti", "to drink"),
        ("voda", "water"),
        ("sok", "juice"),
        ("kafa", "coffee"),
        ("čaj", "tea"),
        ("pivo", "beer"),
        ("vino", "wine"),
        ("rakija", "brandy"),
        ("gaziran", "carbonated"),
        ("toplo", "hot"),
        ("hladno", "cold"),
        ("slatko", "sweet"),
        ("slano", "salty"),
        ("kiselo", "sour"),
        ("gorko", "bitter"),
        ("ljuto", "spicy"),
        ("svež", "fresh"),
        ("ukusno", "delicious"),
        ("restoran", "restaurant"),
        ("kafić", "café"),
        ("pekara", "bakery"),
        ("prodavnica", "store"),
        ("pijaca", "market"),
        ("recept", "recipe"),
        ("sastojak", "ingredient"),
        ("porcija", "portion"),
        ("obrok", "meal"),
    ],
    "Travel": [
        ("putovanje", "travel/journey"),
        ("put", "trip/road"),
        ("destinacija", "destination"),
        ("odmor", "vacation"),
        ("turista", "tourist"),
        ("turizam", "tourism"),
        ("agencija", "agency"),
        ("vodič", "guide"),
        ("tura", "tour"),
        ("rezervacija", "reservation"),
        ("hotel", "hotel"),
        ("soba", "room"),
        ("recepcija", "reception"),
        ("ključ", "key"),
        ("krevet", "bed"),
        ("kupatilo", "bathroom"),
        ("balkon", "balcony"),
        ("pogled", "view"),
        ("doručak", "breakfast"),
        ("polupansion", "half board"),
        ("pun pansion", "full board"),
        ("aerodrom", "airport"),
        ("avion", "airplane"),
        ("let", "flight"),
        ("karta", "ticket"),
        ("pasoš", "passport"),
        ("viza", "visa"),
        ("granica", "border"),
        ("carina", "customs"),
        ("prtljag", "luggage"),
        ("kofer", "suitcase"),
        ("ranac", "backpack"),
        ("torba", "bag"),
        ("autobus", "bus"),
        ("voz", "train"),
        ("auto", "car"),
        ("taksi", "taxi"),
        ("brod", "ship"),
        ("trajekt", "ferry"),
        ("stanica", "station"),
        ("peron", "platform"),
        ("raspored", "schedule"),
        ("kašnjenje", "delay"),
        ("polazak", "departure"),
        ("dolazak", "arrival"),
        ("transfer", "transfer"),
        ("veza", "connection"),
        ("plaža", "beach"),
        ("more", "sea"),
        ("okean", "ocean"),
        ("pesak", "sand"),
        ("sunce", "sun"),
        ("krema za sunčanje", "sunscreen"),
        ("plivanje", "swimming"),
        ("ronjenje", "diving"),
        ("surfovanje", "surfing"),
        ("planina", "mountain"),
        ("planinarenje", "hiking"),
        ("skijanje", "skiing"),
        ("snowboard", "snowboarding"),
        ("kampovanje", "camping"),
        ("šator", "tent"),
        ("priroda", "nature"),
        ("nacionalni park", "national park"),
        ("grad", "city"),
        ("selo", "village"),
        ("centar", "center"),
        ("ulica", "street"),
        ("trg", "square"),
        ("most", "bridge"),
        ("spomenik", "monument"),
        ("muzej", "museum"),
        ("galerija", "gallery"),
        ("crkva", "church"),
        ("manastir", "monastery"),
        ("zamak", "castle"),
        ("tvrđava", "fortress"),
        ("razgledanje", "sightseeing"),
        ("fotografisanje", "photography"),
        ("suvenir", "souvenir"),
        ("razglednica", "postcard"),
        ("mapa", "map"),
        ("GPS", "GPS"),
        ("smeštaj", "accommodation"),
        ("hostel", "hostel"),
        ("apartman", "apartment"),
        ("kamp", "campground"),
        ("osiguranje", "insurance"),
        ("budžet", "budget"),
        ("trošak", "expense"),
        ("menjačnica", "exchange office"),
        ("valuta", "currency"),
        ("kreditna kartica", "credit card"),
        ("gotovina", "cash"),
        ("račun", "bill"),
        ("napojnica", "tip"),
        ("jezik", "language"),
        ("prevod", "translation"),
        ("kultura", "culture"),
        ("tradicija", "tradition"),
        ("običaj", "custom"),
        ("iskustvo", "experience"),
        ("avantura", "adventure"),
        ("sećanje", "memory"),
        ("preporuka", "recommendation"),
    ],
    "Health": [
        ("zdravlje", "health"),
        ("bolest", "illness/disease"),
        ("bol", "pain"),
        ("temperatura", "temperature"),
        ("groznica", "fever"),
        ("prehlada", "cold"),
        ("grip", "flu"),
        ("kašalj", "cough"),
        ("kijanje", "sneezing"),
        ("glavobolja", "headache"),
        ("stomačni bol", "stomach ache"),
        ("mučnina", "nausea"),
        ("povraćanje", "vomiting"),
        ("dijareja", "diarrhea"),
        ("alergija", "allergy"),
        ("osip", "rash"),
        ("svrab", "itch"),
        ("otok", "swelling"),
        ("infekcija", "infection"),
        ("upala", "inflammation"),
        ("povreda", "injury"),
        ("prelom", "fracture"),
        ("uganuće", "sprain"),
        ("modrica", "bruise"),
        ("rana", "wound"),
        ("krvarenje", "bleeding"),
        ("zavoj", "bandage"),
        ("gips", "cast"),
        ("štake", "crutches"),
        ("invalidska kolica", "wheelchair"),
        ("lek", "medicine/drug"),
        ("tableta", "pill/tablet"),
        ("kapsula", "capsule"),
        ("sirup", "syrup"),
        ("injekcija", "injection"),
        ("vakcina", "vaccine"),
        ("antibiotik", "antibiotic"),
        ("analgetik", "painkiller"),
        ("vitamini", "vitamins"),
        ("recept", "prescription"),
        ("doza", "dose"),
        ("nuspojava", "side effect"),
        ("doktor", "doctor"),
        ("lekar", "physician"),
        ("medicinska sestra", "nurse"),
        ("pacijent", "patient"),
        ("bolnica", "hospital"),
        ("klinika", "clinic"),
        ("ambulanta", "outpatient clinic"),
        ("hitna pomoć", "emergency"),
        ("operacija", "surgery"),
        ("anestezija", "anesthesia"),
        ("pregled", "examination"),
        ("dijagnoza", "diagnosis"),
        ("terapija", "therapy"),
        ("lečenje", "treatment"),
        ("oporavak", "recovery"),
        ("rehabilitacija", "rehabilitation"),
        ("fizikalna terapija", "physical therapy"),
        ("laboratorija", "laboratory"),
        ("analiza krvi", "blood test"),
        ("analiza urina", "urine test"),
        ("rendgen", "X-ray"),
        ("ultrazvuk", "ultrasound"),
        ("skener", "CT scan"),
        ("magnetna rezonanca", "MRI"),
        ("EKG", "ECG"),
        ("pritisak", "blood pressure"),
        ("puls", "pulse"),
        ("disanje", "breathing"),
        ("srce", "heart"),
        ("pluća", "lungs"),
        ("jetra", "liver"),
        ("bubrezi", "kidneys"),
        ("želudac", "stomach"),
        ("mozak", "brain"),
        ("kosti", "bones"),
        ("mišići", "muscles"),
        ("krv", "blood"),
        ("koža", "skin"),
        ("oči", "eyes"),
        ("uši", "ears"),
        ("nos", "nose"),
        ("usta", "mouth"),
        ("zubi", "teeth"),
        ("zubar", "dentist"),
        ("plomba", "filling"),
        ("krunica", "crown"),
        ("proteza", "denture"),
        ("vid", "vision"),
        ("naočare", "glasses"),
        ("sočiva", "contact lenses"),
        ("sluh", "hearing"),
        ("slušni aparat", "hearing aid"),
        ("mentalno zdravlje", "mental health"),
        ("stres", "stress"),
        ("anksioznost", "anxiety"),
        ("depresija", "depression"),
        ("psiholog", "psychologist"),
        ("psihijatar", "psychiatrist"),
        ("terapija", "therapy"),
        ("meditacija", "meditation"),
        ("vežbanje", "exercise"),
        ("ishrana", "nutrition"),
        ("dijeta", "diet"),
        ("zdrav", "healthy"),
        ("bolestan", "sick"),
        ("prevencija", "prevention"),
    ],
}


def populate_top_100_words():
    """Populate the database with top 100 words for each category"""

    with engine.connect() as conn:
        # Start a transaction
        trans = conn.begin()

        try:
            # Get or create categories
            category_map = {}

            # First, get existing categories
            result = conn.execute(text("SELECT id, name FROM categories"))
            existing_categories = {row.name: row.id for row in result}

            # Create missing categories
            for category_name in TOP_100_WORDS.keys():
                if category_name in existing_categories:
                    category_map[category_name] = existing_categories[category_name]
                else:
                    result = conn.execute(
                        text(
                            "INSERT INTO categories (name, description) VALUES (:name, :desc) RETURNING id"
                        ),
                        {
                            "name": category_name,
                            "desc": f"Top 100 {category_name} words",
                        },
                    )
                    category_map[category_name] = result.scalar()

            # Now add/update words
            word_count = 0
            updated_count = 0

            for category_name, words in TOP_100_WORDS.items():
                category_id = category_map[category_name]

                for serbian_word, english_translation in words:
                    # Check if word already exists with same serbian word and english translation
                    result = conn.execute(
                        text(
                            "SELECT id FROM words WHERE serbian_word = :word AND english_translation = :english"
                        ),
                        {"word": serbian_word, "english": english_translation},
                    )
                    existing = result.fetchone()

                    if not existing:
                        # Check if there's a word with just the serbian part (different translation)
                        result = conn.execute(
                            text("SELECT id FROM words WHERE serbian_word = :word"),
                            {"word": serbian_word},
                        )
                        similar = result.fetchone()

                        if similar:
                            print(
                                f"Similar word exists: {serbian_word} (different translation)"
                            )

                        # Insert the word
                        conn.execute(
                            text(
                                """
                                INSERT INTO words (serbian_word, english_translation, category_id, is_top_100)
                                VALUES (:serbian, :english, :cat_id, TRUE)
                            """
                            ),
                            {
                                "serbian": serbian_word,
                                "english": english_translation,
                                "cat_id": category_id,
                            },
                        )
                        word_count += 1
                        print(f"Inserted: {serbian_word} - {english_translation}")
                    else:
                        # Update existing word to mark as top 100 and update category if needed
                        conn.execute(
                            text(
                                "UPDATE words SET is_top_100 = TRUE, category_id = :cat_id WHERE id = :id"
                            ),
                            {"id": existing.id, "cat_id": category_id},
                        )
                        updated_count += 1
                        print(f"Updated: {serbian_word} - {english_translation}")

            # Commit all changes
            trans.commit()
            print(f"\nSuccessfully added {word_count} new words to the database")
            print(f"Updated {updated_count} existing words")
            print(f"Categories created/updated: {', '.join(category_map.keys())}")

        except Exception as e:
            trans.rollback()
            print(f"Error during population: {e}")
            raise


if __name__ == "__main__":
    # First, we need to add the is_top_100 column if it doesn't exist
    with engine.connect() as conn:
        try:
            conn.execute(
                text("ALTER TABLE words ADD COLUMN is_top_100 BOOLEAN DEFAULT FALSE")
            )
            conn.commit()
            print("Added is_top_100 column to words table")
        except Exception as e:
            print("Column is_top_100 might already exist or error occurred:", str(e))

    # Now populate the words
    populate_top_100_words()
